name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run CI
        run: make ci
      - name: Upload CodeCov
        env:
          CODECOV_TOKEN: ${{ secrets.CODE_COV_UPLOAD_TOKEN }}
        run: make codecov
      - name: Upload SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_UPLOAD_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make sonar